import type { BlockMeta } from '@/lib/blocks';

const meta: BlockMeta = {
  key: 'testimonials-carousel',
  label: 'Testimonials Carousel',
  sectionType: 'testimonials',
  description:
    'A horizontal scrollable row of testimonial cards. Each card holds a short quote, author name, and context line. Cards are wide enough that 1.5-2 are visible at once on desktop, prompting horizontal scrolling. The row scrolls horizontally via native scroll with snap points, no external carousel library.',
  status: 'active',
  pageTypes: ['home'],
  slots: [],
  contentSchema: [
    {
      key: 'eyebrow',
      type: 'text',
      label: 'Small label above the row',
      required: false,
      aiGenerated: true,
      maxLength: 40,
    },
    {
      key: 'headline',
      type: 'text',
      label: 'Section headline',
      required: false,
      aiGenerated: true,
      maxLength: 80,
    },
    {
      key: 'quote_1',
      type: 'text',
      label: 'Quote 1',
      required: true,
      aiGenerated: true,
      maxLength: 280,
    },
    {
      key: 'author_1',
      type: 'text',
      label: 'Author 1',
      required: true,
      aiGenerated: true,
      maxLength: 60,
    },
    {
      key: 'context_1',
      type: 'text',
      label: 'Context 1',
      required: false,
      aiGenerated: true,
      maxLength: 80,
    },
    {
      key: 'quote_2',
      type: 'text',
      label: 'Quote 2',
      required: true,
      aiGenerated: true,
      maxLength: 280,
    },
    {
      key: 'author_2',
      type: 'text',
      label: 'Author 2',
      required: true,
      aiGenerated: true,
      maxLength: 60,
    },
    {
      key: 'context_2',
      type: 'text',
      label: 'Context 2',
      required: false,
      aiGenerated: true,
      maxLength: 80,
    },
    {
      key: 'quote_3',
      type: 'text',
      label: 'Quote 3',
      required: true,
      aiGenerated: true,
      maxLength: 280,
    },
    {
      key: 'author_3',
      type: 'text',
      label: 'Author 3',
      required: true,
      aiGenerated: true,
      maxLength: 60,
    },
    {
      key: 'context_3',
      type: 'text',
      label: 'Context 3',
      required: false,
      aiGenerated: true,
      maxLength: 80,
    },
    {
      key: 'quote_4',
      type: 'text',
      label: 'Quote 4',
      required: false,
      aiGenerated: true,
      maxLength: 280,
    },
    {
      key: 'author_4',
      type: 'text',
      label: 'Author 4',
      required: false,
      aiGenerated: true,
      maxLength: 60,
    },
    {
      key: 'context_4',
      type: 'text',
      label: 'Context 4',
      required: false,
      aiGenerated: true,
      maxLength: 80,
    },
    {
      key: 'quote_5',
      type: 'text',
      label: 'Quote 5',
      required: false,
      aiGenerated: true,
      maxLength: 280,
    },
    {
      key: 'author_5',
      type: 'text',
      label: 'Author 5',
      required: false,
      aiGenerated: true,
      maxLength: 60,
    },
    {
      key: 'context_5',
      type: 'text',
      label: 'Context 5',
      required: false,
      aiGenerated: true,
      maxLength: 80,
    },
  ],
};

export default meta;
