import type { BlockMeta } from '@/lib/blocks';

const meta: BlockMeta = {
  key: 'testimonials-featured',
  label: 'Featured Testimonial',
  sectionType: 'testimonials',
  description:
    'A single oversized testimonial quote rendered as the focal point of the section, set in display type. The block rotates through 3-5 testimonials with a cross-fade transition every few seconds. Pauses on hover. Author name and context line sit below each quote.',
  status: 'active',
  pageTypes: ['home'],
  slots: [],
  contentSchema: [
    {
      key: 'eyebrow',
      type: 'text',
      label: 'Small label above the quotes',
      required: false,
      aiGenerated: true,
      maxLength: 40,
    },
    {
      key: 'quote_1',
      type: 'text',
      label: 'Quote 1',
      required: true,
      aiGenerated: true,
      maxLength: 320,
    },
    {
      key: 'author_1',
      type: 'text',
      label: 'Author 1',
      required: true,
      aiGenerated: true,
      maxLength: 60,
    },
    {
      key: 'context_1',
      type: 'text',
      label: 'Context 1 (e.g. city, what they bought)',
      required: false,
      aiGenerated: true,
      maxLength: 80,
    },
    {
      key: 'quote_2',
      type: 'text',
      label: 'Quote 2',
      required: true,
      aiGenerated: true,
      maxLength: 320,
    },
    {
      key: 'author_2',
      type: 'text',
      label: 'Author 2',
      required: true,
      aiGenerated: true,
      maxLength: 60,
    },
    {
      key: 'context_2',
      type: 'text',
      label: 'Context 2',
      required: false,
      aiGenerated: true,
      maxLength: 80,
    },
    {
      key: 'quote_3',
      type: 'text',
      label: 'Quote 3',
      required: true,
      aiGenerated: true,
      maxLength: 320,
    },
    {
      key: 'author_3',
      type: 'text',
      label: 'Author 3',
      required: true,
      aiGenerated: true,
      maxLength: 60,
    },
    {
      key: 'context_3',
      type: 'text',
      label: 'Context 3',
      required: false,
      aiGenerated: true,
      maxLength: 80,
    },
    {
      key: 'quote_4',
      type: 'text',
      label: 'Quote 4 (optional)',
      required: false,
      aiGenerated: true,
      maxLength: 320,
    },
    {
      key: 'author_4',
      type: 'text',
      label: 'Author 4',
      required: false,
      aiGenerated: true,
      maxLength: 60,
    },
    {
      key: 'context_4',
      type: 'text',
      label: 'Context 4',
      required: false,
      aiGenerated: true,
      maxLength: 80,
    },
    {
      key: 'quote_5',
      type: 'text',
      label: 'Quote 5 (optional)',
      required: false,
      aiGenerated: true,
      maxLength: 320,
    },
    {
      key: 'author_5',
      type: 'text',
      label: 'Author 5',
      required: false,
      aiGenerated: true,
      maxLength: 60,
    },
    {
      key: 'context_5',
      type: 'text',
      label: 'Context 5',
      required: false,
      aiGenerated: true,
      maxLength: 80,
    },
  ],
};

export default meta;
