/**
 * Boutique, nursery design — the one home for the UI strings the renderer paints
 * itself. Everything the owner wrote (story, headline, babies, dates) comes from
 * the backend, never from here.
 */
export const NURSERY_STRINGS = {
  nav: {
    label: 'Main',
    menu: 'Menu',
    close: 'Close',
    nursery: 'The nursery',
    gone: 'Gone home',
    artist: 'The artist',
    visit: 'Visiting hours',
    touch: 'Ask about a baby',
    home: 'Home',
  },
  hero: { meet: 'Meet the babies', from: (price: string) => `Adoption from ${price}` },
  card: {
    hello: 'Hello, my name is',
    fee: 'Adoption fee',
    ready: 'Ready to go home',
    adopted: 'Adopted',
    open: (name: string) => `Meet ${name}`,
  },
  nursery: {
    tag: 'In the nursery now',
    title: 'Waiting to go home',
    count: (n: number) => (n === 1 ? 'One baby waiting' : `${n} babies waiting`),
    all: (n: number) => `Meet all ${n} babies`,
    empty: 'The nursery is quiet right now. New babies are on the way.',
  },
  gone: {
    tag: 'Gone home',
    title: 'Babies who found their families',
    open: (caption: string, n: number) =>
      caption === '' ? `Open photo ${n}` : `Open photo: ${caption}`,
  },
  sale: {
    banner: (name: string, percent: number) => `${name} · ${percent}% off every baby`,
    until: (day: string) => `until ${day}`,
    was: 'Was',
  },
  market: {
    tag: 'At the market',
    where: (town: string, booth: string) => [town, booth].filter((s) => s !== '').join(' · '),
    before: 'See you at the market. Here’s who’s coming with me.',
    after: 'This market is over. Thank you for visiting! Every baby still waiting is in the nursery.',
    canceled: 'This market was canceled. Every baby is waiting in the nursery.',
    toSite: 'Visit the nursery',
    pick: 'Tap the baby going home with you',
    none: 'No babies are listed for this market yet. Please ask at the table.',
    noPay: 'Please ask at the table to adopt.',
    back: 'Back to the babies',
    yourName: 'Your first name',
    yourEmail: 'Email for a receipt (optional)',
    payWith: 'How are you paying?',
    code: 'Discount code (optional)',
    continue: 'Continue to pay',
    holding: 'Holding your baby…',
    payTitle: (piece: string) => `${piece} is held for you`,
    amount: 'Your total',
    discount: (label: string, amount: string) => `${label}: −${amount}`,
    open: (app: string) => `Open ${app}`,
    send: (app: string, handle: string) => `Send it to ${handle} on ${app}.`,
    zelle: (handle: string) => `Send it with Zelle to ${handle}.`,
    copy: 'Copy',
    copied: 'Copied',
    cash: 'Pay at the table.',
    paid: 'I paid',
    sending: 'One moment…',
    another: 'Pick a different baby',
    doneTitle: (name: string) => `Thank you, ${name}!`,
    done: (piece: string) => `I’ll confirm your payment at the table, then ${piece} is all yours.`,
    order: (n: string) => `Order #${n}`,
    error: 'That didn’t go through. Please try again, or ask at the table.',
    errorNetwork: 'Couldn’t reach the nursery. Check your signal and try again.',
  },
  born: {
    tag: 'Just born',
    title: 'New in the nursery',
    welcome: 'Welcome',
    bornAt: (shop: string) => `Born at ${shop}`,
    ribbon: 'Newborn',
  },
  artist: { tag: 'From the artist' },
  visit: {
    tag: 'Visiting hours',
    title: 'Come say hello in person',
    locale: 'en-US',
    range: (first: string, last: string) => `${first} – ${last}`,
    canceled: 'Canceled',
    directions: 'Directions',
    website: 'Market website',
    directionsLabel: (market: string) => `Directions to ${market}`,
    websiteLabel: (market: string) => `${market} website`,
  },
  touch: {
    tag: 'Ask about a baby',
    title: 'Fell in love with someone?',
    lede: 'Tell me which baby caught your eye, and I’ll answer every question.',
    call: 'Call or text',
    facebook: 'Find me on Facebook',
    instagram: 'Instagram',
  },
  certificate: {
    title: 'Certificate of Birth',
    name: 'Name',
    about: 'About this baby',
    born: 'Born at',
    artist: 'Artist',
    fee: 'Adoption fee',
    status: 'Status',
    adopt: (name: string) => `Ask to adopt ${name}`,
    back: 'Back to the nursery',
    photo: (name: string, n: number) => `${name}, photo ${n}`,
    showPhoto: (n: number) => `Show photo ${n}`,
  },
  shop: { title: 'The nursery' },
  cart: {
    link: (n: number) => (n === 0 ? 'Cart' : `Cart · ${n}`),
    add: 'Add to cart',
    inCart: 'In your cart',
    full: 'Your cart is full. Send this order first, then add more.',
    ask: (name: string) => `Ask about ${name}`,
    tag: 'Going home',
    title: 'Your cart',
    empty: 'Your cart is empty. Every baby in the nursery is waiting to meet you.',
    browse: 'Meet the babies',
    remove: 'Take out',
    removeLabel: (name: string) => `Take ${name} out of your cart`,
    gone: 'No longer available',
    subtotal: 'Babies',
    total: 'Total',
    discount: (label: string) => `Discount (${label})`,
    codeField: 'Discount code',
    codeApply: 'Apply',
    codeApplying: 'Applying…',
    codeRemove: 'Remove code',
    codeApplied: (code: string) => `Code ${code} applied`,
    sendTitle: 'Send your order',
    sendLede: 'Nothing is charged here. I’ll get back to you to arrange payment and how your baby gets home.',
    name: 'Your name',
    email: 'Email',
    phone: 'Phone (optional)',
    note: 'Anything I should know? (optional)',
    honeypot: 'Leave this empty',
    send: 'Send my order',
    sending: 'Sending…',
    fix: 'Take out the babies who are no longer available to send the rest.',
    sentTitle: (n: string) => `Order #${n} is on its way to me`,
    sent: 'Thank you! I’ll be in touch soon.',
    error: 'Your order didn’t send. Please try again.',
    errorNetwork: 'Couldn’t reach the nursery. Check your connection and try again.',
  },
  footer: {
    empowered: 'Empowered by BohdiAI',
    terms: 'Terms',
    privacy: 'Privacy',
    year: (y: number, name: string) => `© ${y} ${name}`,
  },
} as const;
